# modules/tax_report.py

import os
import json
import pandas as pd
import streamlit as st
from datetime import datetime

from utils.common import load_clients

from modules.tax_report_template import (
    get_all_clauses,
    get_clause_title,
    get_clause_sheet,
    get_clause_fields,
    get_tax_audit_form_fields,
    get_tax_audit_form_title,
    get_tax_audit_form_code,
    is_valid_tax_audit_form
)


# ---------------------------------------------------------
# PATH HELPERS
# ---------------------------------------------------------

def get_tax_report_folder(client_name, ay):
    folder = f"clients/{client_name}/AY {ay}/Tax Report"
    os.makedirs(folder, exist_ok=True)
    return folder


def get_applicability_folder(client_name, ay):
    folder = f"clients/{client_name}/AY {ay}/Tax Audit Applicability"
    os.makedirs(folder, exist_ok=True)
    return folder


def get_tax_report_json_path(client_name, ay):
    return f"{get_tax_report_folder(client_name, ay)}/tax_audit_report.json"


def get_old_form_3cd_json_path(client_name, ay):
    return f"{get_tax_report_folder(client_name, ay)}/form_3cd_tax_report.json"


def get_applicability_excel_path(client_name, ay):
    return f"{get_applicability_folder(client_name, ay)}/tax_audit_applicability_result.xlsx"


def get_applicability_json_path(client_name, ay):
    return f"{get_applicability_folder(client_name, ay)}/tax_audit_applicability_result.json"


# ---------------------------------------------------------
# BASIC HELPERS
# ---------------------------------------------------------

def safe_value(value, default=""):
    if value is None:
        return default

    try:
        if pd.isna(value):
            return default
    except:
        pass

    return value


def normalize_audit_form(value):
    """
    Converts different possible labels into standard form names.
    """
    value = str(value or "").strip()

    if "3CA" in value.upper():
        return "Form 3CA-3CD"

    if "3CB" in value.upper():
        return "Form 3CB-3CD"

    if value in ["Form 3CA-3CD", "Form 3CB-3CD"]:
        return value

    return "Not Applicable"


def default_report_structure(audit_form="Not Applicable"):
    return {
        "meta": {
            "audit_form": audit_form,
            "form_code": get_tax_audit_form_code(audit_form),
            "created_on": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "last_updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        },
        "applicability": {},
        "report_form": {},
        "form_3cd": {}
    }


# ---------------------------------------------------------
# APPLICABILITY RESULT READER
# ---------------------------------------------------------

def load_tax_audit_applicability_result(client_name, ay):
    """
    Reads output from Tax Audit Applicability module.

    Priority:
    1. JSON result, if available
    2. Excel result generated by existing applicability module

    Expected Excel columns:
    - Audit Form
    - Section Reference
    - ITR Basis
    - Tax Audit Applicable
    """

    result = {
        "tax_audit_applicable": "",
        "audit_form": "Not Applicable",
        "section_reference": "",
        "itr_basis": "",
        "itr_form": "",
        "reason": ""
    }

    json_path = get_applicability_json_path(client_name, ay)
    excel_path = get_applicability_excel_path(client_name, ay)

    if os.path.exists(json_path):
        try:
            with open(json_path, "r", encoding="utf-8") as file:
                data = json.load(file)

            result["tax_audit_applicable"] = safe_value(data.get("Tax Audit Applicable", data.get("tax_audit_applicable", "")))
            result["audit_form"] = normalize_audit_form(data.get("Audit Form", data.get("audit_form", "Not Applicable")))
            result["section_reference"] = safe_value(data.get("Section Reference", data.get("section_reference", "")))
            result["itr_basis"] = safe_value(data.get("ITR Basis", data.get("itr_basis", "")))
            result["itr_form"] = safe_value(data.get("ITR Form", data.get("itr_form", "")))
            result["reason"] = safe_value(data.get("Reason", data.get("reason", "")))

            return result

        except Exception as e:
            st.warning(f"Could not read applicability JSON. Reason: {e}")

    if os.path.exists(excel_path):
        try:
            df = pd.read_excel(excel_path)

            if len(df) > 0:
                row = df.iloc[0]

                result["tax_audit_applicable"] = safe_value(row.get("Tax Audit Applicable", ""))
                result["audit_form"] = normalize_audit_form(row.get("Audit Form", "Not Applicable"))
                result["section_reference"] = safe_value(row.get("Section Reference", ""))
                result["itr_basis"] = safe_value(row.get("ITR Basis", ""))
                result["itr_form"] = safe_value(row.get("ITR Form", ""))
                result["reason"] = safe_value(row.get("Reason", ""))

                return result

        except Exception as e:
            st.warning(f"Could not read applicability Excel. Reason: {e}")

    return result


# ---------------------------------------------------------
# LOAD / SAVE TAX REPORT
# ---------------------------------------------------------

def load_tax_report(client_name, ay):
    """
    Loads latest tax audit report JSON.

    Also supports old file:
    form_3cd_tax_report.json

    If old file exists, it is migrated into new structure.
    """

    file_path = get_tax_report_json_path(client_name, ay)

    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as file:
            return json.load(file)

    old_file_path = get_old_form_3cd_json_path(client_name, ay)

    if os.path.exists(old_file_path):
        with open(old_file_path, "r", encoding="utf-8") as file:
            old_3cd_data = json.load(file)

        migrated = default_report_structure()
        migrated["form_3cd"] = old_3cd_data

        save_tax_report(client_name, ay, migrated)
        return migrated

    return default_report_structure()


def save_tax_report(client_name, ay, report_data):
    report_data.setdefault("meta", {})
    report_data["meta"]["last_updated"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    file_path = get_tax_report_json_path(client_name, ay)

    with open(file_path, "w", encoding="utf-8") as file:
        json.dump(report_data, file, indent=4, ensure_ascii=False)


# ---------------------------------------------------------
# AUTO PREFILL FROM APPLICABILITY
# ---------------------------------------------------------

def apply_applicability_to_report(report_data, applicability_data):
    """
    Applies audit form and Section 44AB reference from applicability tab.
    """

    audit_form = normalize_audit_form(applicability_data.get("audit_form", "Not Applicable"))

    report_data.setdefault("meta", {})
    report_data.setdefault("applicability", {})
    report_data.setdefault("form_3cd", {})
    report_data.setdefault("report_form", {})

    report_data["meta"]["audit_form"] = audit_form
    report_data["meta"]["form_code"] = get_tax_audit_form_code(audit_form)

    report_data["applicability"] = applicability_data

    # Auto-fill Clause 8 of Form 3CD
    clause_8_existing = report_data["form_3cd"].get("8", {})
    clause_8_fields = clause_8_existing.get("fields", {})

    if applicability_data.get("section_reference"):
        clause_8_fields.setdefault(
            "Relevant clause of section 44AB",
            applicability_data.get("section_reference", "")
        )

    if applicability_data.get("reason"):
        clause_8_fields.setdefault(
            "Reason for applicability",
            applicability_data.get("reason", "")
        )

    clause_8_fields.setdefault(
        "Whether auto-filled from Tax Audit Applicability module",
        "Yes"
    )

    report_data["form_3cd"]["8"] = {
        "title": get_clause_title("8"),
        "utility_sheet": get_clause_sheet("8"),
        "status": clause_8_existing.get("status", "In Progress"),
        "remarks": clause_8_existing.get("remarks", "Auto-filled from Tax Audit Applicability module."),
        "fields": clause_8_fields
    }

    return report_data


# ---------------------------------------------------------
# EXPORT
# ---------------------------------------------------------

def export_tax_audit_report_excel(client_name, ay, report_data):
    """
    Exports full report:
    1. Report Info
    2. Form 3CA / 3CB report level data
    3. Form 3CD clause summary
    4. Form 3CD field details
    """

    folder = get_tax_report_folder(client_name, ay)

    audit_form = report_data.get("meta", {}).get("audit_form", "Not Applicable")
    form_code = report_data.get("meta", {}).get("form_code", "")
    applicability = report_data.get("applicability", {})
    report_form = report_data.get("report_form", {})
    form_3cd = report_data.get("form_3cd", {})

    report_info_df = pd.DataFrame([{
        "Client Name": client_name,
        "Assessment Year": ay,
        "Audit Form": audit_form,
        "Form Code": form_code,
        "Tax Audit Applicable": applicability.get("tax_audit_applicable", ""),
        "Section Reference": applicability.get("section_reference", ""),
        "ITR Basis": applicability.get("itr_basis", ""),
        "ITR Form": applicability.get("itr_form", ""),
        "Generated On": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }])

    report_form_rows = []

    for field_name, field_value in report_form.get("fields", {}).items():
        report_form_rows.append({
            "Audit Form": audit_form,
            "Field": field_name,
            "Value": field_value
        })

    report_form_df = pd.DataFrame(report_form_rows)

    summary_rows = []

    for clause_no, title in get_all_clauses():
        data = form_3cd.get(clause_no, {})
        summary_rows.append({
            "Clause No": clause_no,
            "Title": title,
            "Utility Sheet": get_clause_sheet(clause_no),
            "Filling Status": data.get("status", "Not Filled"),
            "Final Auditor Remark": data.get("remarks", "")
        })

    form_3cd_summary_df = pd.DataFrame(summary_rows)

    detail_rows = []

    for clause_no, title in get_all_clauses():
        data = form_3cd.get(clause_no, {})
        fields = data.get("fields", {})

        if fields:
            for field_name, field_value in fields.items():
                detail_rows.append({
                    "Clause No": clause_no,
                    "Title": title,
                    "Utility Sheet": get_clause_sheet(clause_no),
                    "Field": field_name,
                    "Value": field_value,
                    "Status": data.get("status", "Not Filled"),
                    "Auditor Remark": data.get("remarks", "")
                })
        else:
            detail_rows.append({
                "Clause No": clause_no,
                "Title": title,
                "Utility Sheet": get_clause_sheet(clause_no),
                "Field": "",
                "Value": "",
                "Status": "Not Filled",
                "Auditor Remark": ""
            })

    form_3cd_details_df = pd.DataFrame(detail_rows)

    excel_path = f"{folder}/tax_audit_report_{form_code or 'NA'}_3CD.xlsx"

    with pd.ExcelWriter(excel_path) as writer:
        report_info_df.to_excel(writer, sheet_name="Report_Info", index=False)
        report_form_df.to_excel(writer, sheet_name="3CA_3CB_Report", index=False)
        form_3cd_summary_df.to_excel(writer, sheet_name="Form_3CD_Summary", index=False)
        form_3cd_details_df.to_excel(writer, sheet_name="Form_3CD_Details", index=False)

    return excel_path


# ---------------------------------------------------------
# COMPLETION CALCULATION
# ---------------------------------------------------------

def calculate_completion(report_data):
    form_3cd = report_data.get("form_3cd", {})

    completed_count = 0
    total_count = len(get_all_clauses())

    for clause_no, title in get_all_clauses():
        status = form_3cd.get(clause_no, {}).get("status", "Not Filled")

        if status in ["Filled", "Not Applicable"]:
            completed_count += 1

    completion = round((completed_count / total_count) * 100, 2) if total_count > 0 else 0

    return completed_count, total_count, completion


# ---------------------------------------------------------
# MAIN STREAMLIT UI
# ---------------------------------------------------------

def show_tax_report():
    st.subheader("📑 Tax Audit Report - Form 3CA / 3CB with Form 3CD")

    df = load_clients()

    if df.empty or "Client Name" not in df.columns:
        st.info("Please add clients first.")
        return

    client_list = sorted(df["Client Name"].dropna().unique().tolist())

    if len(client_list) == 0:
        st.info("Please add clients first.")
        return

    selected_client = st.selectbox(
        "Search / Select Client",
        client_list,
        index=0,
        placeholder="Search client name..."
    )

    if not selected_client:
        st.info("Please select a client.")
        return

    selected_row = df[df["Client Name"] == selected_client].iloc[0]
    selected_ay = selected_row["AY"]

    st.write(f"### Client: {selected_client} | AY: {selected_ay}")

    applicability_data = load_tax_audit_applicability_result(selected_client, selected_ay)

    report_data = load_tax_report(selected_client, selected_ay)
    report_data = apply_applicability_to_report(report_data, applicability_data)
    save_tax_report(selected_client, selected_ay, report_data)

    audit_form = report_data.get("meta", {}).get("audit_form", "Not Applicable")
    form_code = report_data.get("meta", {}).get("form_code", "")

    st.divider()

    # ---------------------------------------------------------
    # Applicability Display
    # ---------------------------------------------------------

    st.write("## 🧭 Auto-linked Tax Audit Applicability")

    a1, a2, a3 = st.columns(3)

    with a1:
        st.metric("Tax Audit Applicable", applicability_data.get("tax_audit_applicable", ""))

    with a2:
        st.metric("Audit Form", audit_form)

    with a3:
        st.metric("Section Reference", applicability_data.get("section_reference", ""))

    if audit_form == "Not Applicable":
        st.warning(
            "Tax audit form is not available from the Tax Audit Applicability module. "
            "Please first complete the Tax Audit Applicability tab for this client."
        )
        return

    if not is_valid_tax_audit_form(audit_form):
        st.error("Invalid audit form detected. Please check Tax Audit Applicability result.")
        return

    st.success(f"Applicable report selected automatically: {audit_form}")
    st.caption(get_tax_audit_form_title(audit_form))

    if applicability_data.get("reason"):
        with st.expander("View Applicability Reason"):
            st.write(applicability_data.get("reason"))

    st.divider()

    # ---------------------------------------------------------
    # Form 3CA / 3CB Report Level Entry
    # ---------------------------------------------------------

    st.write(f"## 🧾 {form_code} Report Details")

    report_data.setdefault("report_form", {})
    report_data["report_form"].setdefault("fields", {})

    existing_report_fields = report_data["report_form"].get("fields", {})
    form_fields = get_tax_audit_form_fields(audit_form)

    with st.expander(f"Open {form_code} Report Data Entry", expanded=False):

        updated_report_fields = {}

        for field in form_fields:
            updated_report_fields[field] = st.text_area(
                field,
                value=existing_report_fields.get(field, ""),
                height=70,
                key=f"report_form_{form_code}_{field}"
            )

        if st.button(f"💾 Save {form_code} Report Details"):
            report_data["report_form"] = {
                "audit_form": audit_form,
                "form_code": form_code,
                "title": get_tax_audit_form_title(audit_form),
                "fields": updated_report_fields
            }

            save_tax_report(selected_client, selected_ay, report_data)
            st.success(f"✅ {form_code} report details saved successfully.")
            st.rerun()

    st.divider()

    # ---------------------------------------------------------
    # Form 3CD Clause Table
    # ---------------------------------------------------------

    st.write("## 📋 Form 3CD Clause-wise Reporting")

    latest_report_data = load_tax_report(selected_client, selected_ay)
    form_3cd_data = latest_report_data.get("form_3cd", {})

    clause_rows = []

    for clause_no, title in get_all_clauses():
        saved = form_3cd_data.get(clause_no, {})
        clause_rows.append({
            "Clause No": clause_no,
            "Title / Particulars": title,
            "Utility Sheet": get_clause_sheet(clause_no),
            "Filling Status": saved.get("status", "Not Filled")
        })

    clause_df = pd.DataFrame(clause_rows)

    st.info("Click once on any clause row to open the Form 3CD data entry dialog.")

    selected_event = st.dataframe(
        clause_df,
        use_container_width=True,
        hide_index=True,
        on_select="rerun",
        selection_mode="single-row",
        key="form_3cd_clause_table"
    )

    @st.dialog("Form 3CD Clause Data Entry")
    def open_clause_dialog(clause_no):
        clause_no = str(clause_no)

        clause_title = get_clause_title(clause_no)
        utility_sheet = get_clause_sheet(clause_no)

        latest_data = load_tax_report(selected_client, selected_ay)
        latest_data.setdefault("form_3cd", {})

        existing = latest_data["form_3cd"].get(clause_no, {})
        existing_fields = existing.get("fields", {})

        st.write(f"### Clause {clause_no}")
        st.write(f"**{clause_title}**")
        st.caption(f"Utility Sheet Reference: {utility_sheet}")

        fields = get_clause_fields(clause_no)
        filled_fields = {}

        for field in fields:
            filled_fields[field] = st.text_area(
                field,
                value=existing_fields.get(field, ""),
                height=80,
                key=f"clause_{clause_no}_{field}"
            )

        final_remark = st.text_area(
            "Final Auditor Remark",
            value=existing.get("remarks", ""),
            height=100,
            key=f"clause_{clause_no}_final_remark"
        )

        status_options = [
            "Not Filled",
            "In Progress",
            "Filled",
            "Not Applicable"
        ]

        existing_status = existing.get("status", "Not Filled")

        status = st.selectbox(
            "Filling Status",
            status_options,
            index=status_options.index(existing_status) if existing_status in status_options else 0,
            key=f"clause_{clause_no}_status"
        )

        if st.button("💾 Save Clause", key=f"save_clause_{clause_no}"):
            latest_data["form_3cd"][clause_no] = {
                "title": clause_title,
                "utility_sheet": utility_sheet,
                "status": status,
                "remarks": final_remark,
                "fields": filled_fields
            }

            save_tax_report(selected_client, selected_ay, latest_data)
            st.success("✅ Clause saved successfully.")
            st.rerun()

    selected_rows = selected_event.selection.rows

    if selected_rows:
        row_index = selected_rows[0]
        selected_clause_no = str(clause_df.iloc[row_index]["Clause No"])
        open_clause_dialog(selected_clause_no)

    st.divider()

    # ---------------------------------------------------------
    # Completion & Export
    # ---------------------------------------------------------

    latest_report_data = load_tax_report(selected_client, selected_ay)

    completed_count, total_clauses, completion = calculate_completion(latest_report_data)

    st.subheader("📊 Tax Audit Report Completion")

    c1, c2, c3 = st.columns(3)

    with c1:
        st.metric("Completed Clauses", completed_count)

    with c2:
        st.metric("Total Clauses", total_clauses)

    with c3:
        st.metric("Completion", f"{completion}%")

    st.progress(completion / 100)

    st.divider()

    if st.button("📤 Export Complete Tax Audit Report to Excel"):
        excel_path = export_tax_audit_report_excel(
            selected_client,
            selected_ay,
            latest_report_data
        )
        st.success(f"✅ Exported successfully: {excel_path}")

    st.caption(
        "Note: This module prepares structured working data for Form 3CA/3CB and Form 3CD. "
        "Final JSON upload compatibility can be added in the next enhancement."
    )